### ISSUE TITLE
Vite + React SPA: No styles rendered, missing docs? 

### ISSUE THREAD

**Issue by busticated** [HorusGoul/vite-plugin-stylex#24]
hey there :wave:

thanks for pulling this together. i ran into weirdness trying to get things wired up in a simple demo project (basically [this](https://reactrouter.com/en/main/start/tutorial) - `react`, `react-router-dom`, and `vite`).

i see that classnames - e.g. `x6cbk37`, `x10l5d7b`, etc - are being generated and assigned to my component but the main stylesheet (`.css`) file is not being appended / loaded. do i need to add an `import` or something? the [docs](https://github.com/HorusGoul/vite-plugin-stylex/tree/96fd66b44068155bb53d0837e35ab41f3d3f8246#setup):

> For a basic SPA setup, you only need to add the plugin to your Vite config:

...imply that i do not. 

edit: upon closer inspection, i see an empty style element 🤷‍♂️:

```html
<style type="text/css" data-stylex="true"></style>
```
 
edit, edit: it works when building for _production_ e.g. `vite build && vite preview` 🤔 

```html
<link rel="stylesheet" crossorigin="" href="/bits/index-jNj-DRTq.css">
```

thanks again 👍

**Comment by HorusGoul** [comment]
Hey! Can you upload a reproduction example?

**Comment by busticated** [comment]
@HorusGoul i can. in the meantime, it might be easier to point me at a known-working example. i see you have some for framework usage (remix, etc) but not a simple SPA. is there one out there you are aware of?

**Comment by hendry91** [comment]
May I know are you able to use **vite build --watch**? when I on --watch, if I save something, I will hit **[vite-plugin-stylex] rule is not iterable.**

**Comment by hendry91** [comment]
May I know are you able to use **vite build --watch**? when I use --watch, if I made changes and save, I will hit **[vite-plugin-stylex] rule is not iterable.**

**Comment by busticated** [comment]
@HorusGoul i tried to run the example project but ran into all sorts of errors. are you able to provide instructions on how to run them? i tried installing w/ `pnpm` and running w/ `pnpm run dev` from the root and from the `apps/vite-demo` directory but nothing worked (ex: `Failed to resolve entry for package "vite-plugin-stylex". The package may have incorrect main/module/exports specified in its package.json`, `Missing script: "dev"`, `sh: vite: command not found`, etc).

**Comment by HorusGoul** [comment]
@busticated 

1. `pnpm install` on the root of the monorepo
2. `pnpm turbo run build` on the root of the monorepo
3. `cd apps/vite-demo` to enter the folder of the Vite + React SPA demo
4. `pnpm dev`  

This should work (steps followed in CI before running all tests).

**Comment by busticated** [comment]
@HorusGoul thanks - that got me up and running. your example [`vite-demo` app](https://github.com/HorusGoul/vite-plugin-stylex/tree/main/apps/vite-demo) works as expected out of the box. however, when you use a media query (as shown [here](https://stylexjs.com/docs/learn/theming/defining-variables/#using-media-queries)), `dev` mode breaks as i described in my original post. 

repro steps:

1. install the repo locally using your [instructions](https://github.com/HorusGoul/vite-plugin-stylex/issues/24#issuecomment-1871663299)
2. apply this diff locally

```diff
diff --git a/apps/vite-demo/src/theme.stylex.ts b/apps/vite-demo/src/theme.stylex.ts
index 0fc1af8..19a6a07 100644
--- a/apps/vite-demo/src/theme.stylex.ts
+++ b/apps/vite-demo/src/theme.stylex.ts
@@ -1,5 +1,10 @@
 import * as stylex from "@stylexjs/stylex";
 
+const DARK = '@media (prefers-color-scheme: dark)';
+
 export const tokens = stylex.defineVars({
-  primaryTextColor: "#000",
+  primaryTextColor: {
+    default: 'black',
+    [DARK]: 'white'
+  },
 });
```

3. run the `dev` server: `pnpm dev` 
4. point your browser at http://localhost:5173/

you will see a DOM like:

<img width="941" alt="Screenshot 2023-12-29 at 9 07 36 AM" src="https://github.com/HorusGoul/vite-plugin-stylex/assets/367674/619dec38-fe62-40ce-80fc-409186bb8251">

note that the `data-testid="card"` element has stylex classnames assigned but those classnames do not correspond to any actual style definitions and thus the element is visually unstyled. 

hope it helps - thanks again for working on this 🙏 👍

**Comment by busticated** [comment]
@HorusGoul nice! sounds good - thanks again for chasing this down 🙏 👍

**Comment by lecstor** [comment]
> May I know are you able to use **vite build --watch**? when I use --watch, if I made changes and save, I will hit **[vite-plugin-stylex] rule is not iterable.**

@hendry91 did you ever work out what was causing this? I'm seeing it now with latest versions of everything but can find any reference to "rule is not iterable" anywhere..
