### ISSUE TITLE
Build stylex in production mode with non-production vite mode

### ISSUE THREAD

**Issue by olivierpascal** [HorusGoul/vite-plugin-stylex#42]
I would like to build stylex in production mode with an arbitrary mode (ie. `vite build --mode staging`).

Today it is not possible:

https://github.com/HorusGoul/vite-plugin-stylex/blob/ce2e330df0f5e2cadf63f5a9d145274a5ee48154/packages/vite-plugin-stylex/src/index.mts#L138-L142

**Comment by HorusGoul** [comment]
Thanks for the report! This should check that we're running Vite with the build command instead.

**Comment by Sparkmasterflex** [comment]
That did it. Thanks!
