### ISSUE TITLE
`.props(...)` method not merging styles as expected

### ISSUE THREAD

**Issue by tyler-dot-earth** [HorusGoul/vite-plugin-stylex#67]
Playing around with `vite-plugin-stylex` and `react-strict-dom`, hit some unexpected behavior when trying to merge styles with `.props` method (`stylex.props` is `css.props` with `react-strict-dom`).

StyleX docs on merging styles, variants, etc:
- https://stylexjs.com/docs/learn/styling-ui/using-styles/

Button code:
- https://github.com/tsnieman/react-strict-dom-stylex-vite-playground/blob/6b45b1720581a16f470b4ee8e8192fff216d4619/src/_components/button.tsx#L50-L61
- https://github.com/tsnieman/react-strict-dom-stylex-vite-playground/blob/6b45b1720581a16f470b4ee8e8192fff216d4619/src/_components/button.stylex.ts

The result is that I have no styles on buttons

![image](https://github.com/HorusGoul/vite-plugin-stylex/assets/595711/52bb1ff2-7dda-46be-911c-51e86aae37ec)

![image](https://github.com/HorusGoul/vite-plugin-stylex/assets/595711/db4db059-9948-496d-b61e-d664cc89deef)

Am I doing this wrong? Is this a bug with `vite-plugin-stylex`?

Thanks

**Comment by necolas** [comment]
This is invalid code when using RSD https://github.com/tyler-dot-earth/react-strict-dom-stylex-vite-playground/blob/6b45b1720581a16f470b4ee8e8192fff216d4619/src/_components/button.tsx#L50-L61

You just pass the styles directly to the `style` prop, no `stylex.props`.

**Comment by HorusGoul** [comment]
@necolas Thanks for the clarification!
