### ISSUE TITLE
upgrade peer dependency of "@stylexjs/stylex": "^0.5.1" to ">=0.5.1" so that version 0.6.0 not throws a warning

### ISSUE THREAD

**Issue by patrickstubner** [HorusGoul/vite-plugin-stylex#72]
StyleX is still on a 0.x version and a peer dependency of ^0.5.1 means only the patch version can change for 0.x versions.
Now there is StyleX 0.6.0, maybe you can upgrade to 0.6.0 as well or change the version in a way that 0.6.0 is at least compatible.

**Comment by RoiEf** [comment]
I'm having the same issue.
at the moment managed to install using:
`npm install --save-dev vite-plugin-stylex --legacy-peer-deps`

**Comment by nikeee** [comment]
Same with 0.9 now. I've opened #89

**Comment by HorusGoul** [comment]
I'm gonna close this issue, until StyleX gets to v1 I won't change the range to `>=` just to be safe from breaking changes. 

It's totally fine to open new issues when a new StyleX minor version drops because it notifies me though!

Thanks :)
