### ISSUE TITLE
BUG: Babel is undefined in Nuxt environments

### ISSUE THREAD

**Issue by nathpaiement** [HorusGoul/vite-plugin-stylex#82]
I can't get the plugin to work inside of a Nuxt environment without doing a little modification.
Here's the error I get on my local machine:
```
 ERROR  Pre-transform error: Cannot read properties of undefined (reading 'transformAsync')
```

And on the following Stackblitz (https://stackblitz.com/edit/nuxt-starter-qaiw8w), I get this error instead:
```
 ERROR  Pre-transform error: _core.default is undefined
```

The little modification I did to solve the issue was to replace `import babel from "@babel/core";` with `import * as babel from "@babel/core";` in the main.mjs file.
Feel free to experiment yourself by running `code ./node_modules/vite-plugin-stylex/dist/main.mjs` in the Stackblitz terminal to make said changes.

While this seems like a little change, I'm not aware of the implications for other environments to suggest this as a PR.

**Comment by HorusGoul** [comment]
Hey! I encourage you to put this up in a PR and try to run tests on the different demo apps that target many different frameworks. If everything works, it should be good to go :smile:

**Comment by nathpaiement** [comment]
Hey! So as you proposed, I made this PR https://github.com/HorusGoul/vite-plugin-stylex/pull/83 and the tests worked.
Happy to see this get merged soon then 😀
