### ISSUE TITLE
Possible to support CSS variable names?

### ISSUE THREAD

**Issue by zaydek** [HorusGoul/vite-plugin-stylex#92]
This may be an issue with StyleX but is it possible so that the CSS variables defined when using are somehow preserved, even if they are hashed?

For example:

```ts
import * as stylex from "@stylexjs/stylex";

export const config = stylex.defineVars({
  sidebarPaddingInline: "8px",
  sidebarPaddingBlock: "24px",
  largeItemBlockSize: "40px",
  largeItemIconSize: "24px",
  smallItemBlockSize: "32px",
  smallItemIconSize: "16px",
});
```

I get:

```css
:root, .x1wgj55z {
  --xnizh6l: 8px;
  --x8vacmc: 24px;
  --x1dvt6oz: 40px;
  --xwy2vh7: 24px;
  --x1szfbyg: 32px;
  --xx87m7u: 16px;
}
```

Where I would expect something more like:

```css
:root, .x1wgj55z {
  --sidebarPaddingInline-xnizh6l: 8px;
  --sidebarPaddingBlock-x8vacmc: 24px;
  --largeItemBlockSize-x1dvt6oz: 40px;
  --largeItemIconSize-xwy2vh7: 24px;
  --smallItemBlockSize-x1szfbyg: 32px;
  --smallItemIconSize-xx87m7u: 16px;
}
```

Is this supportable? Thanks. Tagging @nmn in case he has input.

**Comment by nmn** [comment]
@zaydek This needs to be done on the StyleX side and we already have an issue to do it. It's not a big task, so unless we get a contribution, I'll address this soon.

**Comment by zaydek** [comment]
> @zaydek This needs to be done on the StyleX side and we already have an issue to do it. It's not a big task, so unless we get a contribution, I'll address this soon.

Thanks much appreciated! Will close this on this repo.
